#!/usr/bin/env node
/**
 * Bridge capture setup — the one command a candidate runs.
 *
 *   node capture-kit/setup.js <submission-token>
 *
 * Shows the disclosure, records consent, registers a capture session, and
 * writes the two config files that make it work:
 *   .bridge/config.json      — API base + capture token (gitignored)
 *   .claude/settings.json    — the Claude Code hooks that call our script
 *
 * Consent is a hard gate: the server refuses to open a session without it,
 * and nothing is captured until this has run.
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { execSync } = require("child_process");

// `--local` points at a dev server; handy for testing the kit end to end
// without a real assessment. `--api=` (from the candidate page) and
// BRIDGE_API_URL override the production default.
const LOCAL_API = `http://localhost:${process.env.PORT || 5050}`;
const apiFromArg = process.argv
  .find((a) => a.startsWith("--api="))
  ?.slice("--api=".length);
const DEFAULT_API =
  process.env.BRIDGE_API_URL ||
  apiFromArg ||
  (process.argv.includes("--local")
    ? LOCAL_API
    : "https://bridge-assessements-1.onrender.com");

const DISCLOSURE = `
─────────────────────────────────────────────────────────────
  Bridge — what this assessment records
─────────────────────────────────────────────────────────────

  While you work in THIS folder, Bridge records:

    • the prompts you send to your AI coding assistant
    • the assistant's replies
    • the commands and file edits it makes on your behalf
    • the contents of files you change in this project

  Bridge does NOT record:

    • your screen, camera, or microphone
    • anything outside this project folder
    • other applications, browser tabs, or files on your machine

  Everything sent is mirrored locally to .bridge/sent.jsonl.
  You can read that file at any time to see exactly what was shared.

  Capture stops when the assessment is submitted. To stop earlier,
  delete .claude/settings.json — but note that an incomplete record
  is visible to the reviewer.

─────────────────────────────────────────────────────────────
`;

/**
 * One readline interface for the whole prompt sequence. Creating a fresh one
 * per question closes stdin on the first `.close()`, after which later
 * questions never resolve and node exits silently with no output.
 */
let rl = null;
function ask(question) {
  if (!rl) {
    rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
  }
  return new Promise((resolve) => {
    let settled = false;
    const done = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    // stdin can hit EOF (piped input, non-TTY, CI). Without this the question
    // never resolves, the event loop empties, and node exits 0 having silently
    // done nothing — which looks to the candidate like the setup just failed.
    rl.once("close", () => done(""));
    rl.question(question, (answer) => done(answer.trim()));
  });
}

function closePrompts() {
  if (rl) {
    rl.close();
    rl = null;
  }
}

/** Read `--flag=value` from argv, so the kit can also run unattended. */
function argValue(flag) {
  const hit = process.argv.find((a) => a.startsWith(`${flag}=`));
  return hit ? hit.slice(flag.length + 1) : null;
}

function gitRemote() {
  try {
    return execSync("git config --get remote.origin.url", {
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 1000,
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function hookEntry(eventName, opts = {}) {
  const entry = {
    hooks: [
      { type: "command", command: `node .bridge/bridge-capture.js ${eventName}` },
    ],
  };
  if (opts.matcher) entry.matcher = opts.matcher;
  return [entry];
}

function buildSettings() {
  return {
    // Generated by Bridge capture setup. Delete this file to stop capturing.
    hooks: {
      SessionStart: hookEntry("SessionStart"),
      UserPromptSubmit: hookEntry("UserPromptSubmit"),
      PreToolUse: hookEntry("PreToolUse", { matcher: "*" }),
      PostToolUse: hookEntry("PostToolUse", { matcher: "*" }),
      Stop: hookEntry("Stop"),
      SessionEnd: hookEntry("SessionEnd"),
    },
  };
}

function ensureGitignored(entry) {
  const gitignorePath = path.join(process.cwd(), ".gitignore");
  let current = "";
  try {
    current = fs.readFileSync(gitignorePath, "utf8");
  } catch {
    current = "";
  }
  if (current.split("\n").some((line) => line.trim() === entry)) return;
  const prefix = current && !current.endsWith("\n") ? "\n" : "";
  fs.appendFileSync(gitignorePath, `${prefix}${entry}\n`);
}

async function main() {
  const isLocal = process.argv.includes("--local");
  const submissionToken =
    process.argv.slice(2).find((a) => !a.startsWith("--")) ||
    process.env.BRIDGE_SUBMISSION_TOKEN;

  console.log(DISCLOSURE);
  // A real assessment always carries a token; --local test runs create an
  // unlinked session so the kit can be exercised without one.
  if (!submissionToken && !isLocal) {
    console.error(
      "Missing submission token.\n  Usage: node capture-kit/setup.js <submission-token>\n" +
        "  (or: node capture-kit/setup.js --local   for a local test session)\n"
    );
    process.exit(1);
  }

  const answer = await ask("  Type 'agree' to start the assessment with capture on: ");
  if (answer.toLowerCase() !== "agree") {
    closePrompts();
    console.log("\n  Setup cancelled. Nothing was recorded or sent.\n");
    process.exit(1);
  }

  const candidateName =
    argValue("--name") || (await ask("  Your name (for the reviewer): "));
  closePrompts();

  const apiBase = DEFAULT_API.replace(/\/$/, "");
  let session;
  try {
    const res = await fetch(`${apiBase}/api/workflow-capture/sessions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        submissionToken: submissionToken || undefined,
        candidateName: candidateName || undefined,
        source: "claude-code",
        consentGranted: true,
        environment: {
          cwd: process.cwd(),
          gitRemote: gitRemote(),
          platform: `${process.platform} ${process.arch}`,
          toolVersion: process.version,
        },
      }),
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      const disabledHint =
        res.status === 404 || res.status === 503
          ? "\n  Capture routes are off on this server. For a local test: set WORKFLOW_CAPTURE_ENABLED=true in server/config.env, restart, and pass --local (or --api=http://localhost:5050)."
          : "";
      throw new Error(`HTTP ${res.status} ${body.slice(0, 200)}${disabledHint}`);
    }
    session = await res.json();
  } catch (err) {
    console.error(`\n  Could not reach Bridge: ${err.message}`);
    console.error("  Check your connection and try again.\n");
    process.exit(1);
  }

  const bridgeDir = path.join(process.cwd(), ".bridge");
  const claudeDir = path.join(process.cwd(), ".claude");
  fs.mkdirSync(bridgeDir, { recursive: true });
  fs.mkdirSync(claudeDir, { recursive: true });

  fs.writeFileSync(
    path.join(bridgeDir, "config.json"),
    JSON.stringify(
      { apiBase, captureToken: session.captureToken, sessionId: session.sessionId },
      null,
      2
    )
  );
  for (const script of [
    "bridge-capture.js",
    "cursor-adapter.js",
    "codex-adapter.js",
    "view.js",
  ]) {
    fs.copyFileSync(path.join(__dirname, script), path.join(bridgeDir, script));
  }

  // Codex hooks, best-effort. Codex documents the same event names as Claude
  // Code but its repo-local hook file is trust-gated and we have not verified
  // this schema against a running install — hence the file-based
  // codex-adapter.js, which does not depend on it. Check with /hooks in Codex.
  const codexDir = path.join(process.cwd(), ".codex");
  fs.mkdirSync(codexDir, { recursive: true });
  fs.writeFileSync(
    path.join(codexDir, "hooks.json"),
    JSON.stringify(
      {
        hooks: Object.fromEntries(
          ["SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop", "SessionEnd"].map(
            (evt) => [
              evt,
              [{ hooks: [{ type: "command", command: `node .bridge/bridge-capture.js ${evt}` }] }],
            ]
          )
        ),
      },
      null,
      2
    )
  );
  fs.writeFileSync(
    path.join(claudeDir, "settings.json"),
    JSON.stringify(buildSettings(), null, 2)
  );

  // The capture token is a secret and the local mirror is the candidate's own
  // copy — neither belongs in the repo they submit.
  ensureGitignored(".bridge/");

  console.log(`
  ✅ Capture is on for this folder.

     Session:  ${session.sessionId}
     Sent log: .bridge/sent.jsonl   (read this any time)

     Start working with:  claude

     Claude Code will ask you to trust this folder the first time —
     that prompt is what activates the capture hooks.
`);
}

main().catch((err) => {
  console.error(`Setup failed: ${err.message}`);
  process.exit(1);
});
